-- 0007_matches_sala_num (Task 3 app.swap.salas)
-- O fork navega em `/sala-mod1/:id` (SalaMod1.tsx faz parseInt) e deriva o
-- código de exibição `#${String(sala.id).padStart(6,'0')}` — herança de
-- `salas.id` bigint. O uuid de `matches.id` quebraria os dois. `sala_num` é o
-- id público numérico da sala; o uuid fica interno.

ALTER TABLE "matches" ADD COLUMN "sala_num" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX "matches_sala_num_unique" ON "matches" USING btree ("sala_num");--> statement-breakpoint
